twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'assets/css': styles
        'assets/images': images
    form_themes: ['tailwind_2_layout.html.twig']

when@test:
    twig:
        strict_variables: true
